services:
  - type: web
    plan: free
    name: my-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DJ_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4